### ISSUE TITLE
Optional frame rate for NTSC gives `NaN` for milliseconds

### ISSUE THREAD

**Issue by pietrop** [Synchronized-TV/node-timecodes#2]
in terminal I tried the following

```bash
> var timecodes = require('node-timecodes');
undefined
> timecodes.fromSeconds(1427.4);
'00:23:47:10'
> timecodes.fromSeconds(1427.4, {frameRate: 29.97});
'00:23:47:NaN'
```

There might be an issue with the [fromSeconds](https://github.com/Synchronized-TV/node-/blob/master/src/fromSeconds.js) function?

**Comment by revolunet** [comment]
Hi Pietro, thanks for reporting.

Just added these test cases to the the suite and results look good to me, can you confirm ?
https://github.com/Synchronized-TV/node-timecodes/commit/73a2824aa7bf648256012ed2fed25ab1bfd4451e

Which version are you using ? latest is 2.4.1

**Comment by pietrop** [comment]
Thanks @revolunet  I updated to the latest version and it seems to work fine now.

```
> timecodes.fromSeconds(2237.3, {frameRate: 29.97});
'00:37:17:08'
```

**Comment by revolunet** [comment]
enjoy :)
