### ISSUE TITLE
Globally set default frameRate

### ISSUE THREAD

**Issue by gabrielboliveira** [Synchronized-TV/node-timecodes#3]
It should be possible to globally change the default Framerate to be used by both methods. 

Similar to [axios](https://github.com/axios/axios#config-defaults): 

```js
axios.defaults.baseURL = 'https://api.example.com';
```

For example, I'm using the same frame rate for all method calls, but I have to pass in the frame rate everywhere.

So just as example:

```js
import Timecode from 'node-timecodes'

Timecode.defaults.framerate = 23.976

Timecode.fromSeconds(10)
// uses 23.976 as frameRate, and not 25
```

**Comment by jide** [comment]
It would have been easy to wrap the function with a custom one though : 
```js
// timecodes.23.976.js
export function fromSeconds(seconds, options) {
  return timecodes.fromSeconds(seconds, { ...options, frameRate: 23.976 });
}

export function toSeconds(seconds, frameRate = 23.976) {
  return timecodes.toSeconds(seconds, frameRate);
}
```

**Comment by gabrielboliveira** [comment]
Changing the default config so it globally uses it it's a proper solution, not a workaround. A good number of packages uses this approach, e.g [axios](https://github.com/axios/axios#config-defaults) as I mentioned above. 

Also, me and @ksetoue already did a PR for it :)

**Comment by jide** [comment]
The PR is good :)

But just wanted to point out that composing functions is also a good solution, which works in lots of cases without having to modify the module code ;)

Think of it as "there is a generic solution for these cases when you can't always submit a PR".

```js
// timecodes.js
import timecodes from 'timecodes';

export let defaults = { framerate : 25 };

export function fromSeconds(seconds, options) {
  return timecodes.fromSeconds(seconds, { frameRate: defaults.framerate, ...options });
}

export function toSeconds(seconds, frameRate = defaults.framerate) {
  return timecodes.toSeconds(seconds, frameRate);
}
```

```js
// app.js
import timecodes from './timecodes';

timecodes.defaults.framerate = 23.976

timecodes.fromSeconds(10)
```

**Comment by gabrielboliveira** [comment]
For sure, I agree with you. That's actually what we did on our app until the PR is accepted (or not haha).

But not a fan of creating a workaround and ignoring the PR part. What about contributing? :)

**Comment by jide** [comment]
Oh not what I meant, the PR will be absolutely be merged, and a new release done, did not mean to ignore anything.

Thanks for the submission and the attention to details ! (I am a co-maintainer of this repo myself, will just bring attention from @revolunet on this).

**Comment by revolunet** [comment]
thanks @gabrielboliveira and @ksetoue for the PR, with tests included 👍

And thanks @jide for the "workaround" :)

I'm not in charge of this repo anymore but im sure this could be merged and published soon.

Also, would be nice to add to add circleci for PR+test ?

**Comment by jide** [comment]
The PR has been merged and a new release published.

Thank you a lot @gabrielboliveira and @ksetoue !
